### ISSUE TITLE
sddm will not start after the upgrade.

### ISSUE THREAD

**Issue by ianporter** [corngood/archlinux-amdgpu#32]
[21:30:26.364] (II) DAEMON: Initializing...
[21:30:26.409] (II) DAEMON: Starting...
[21:30:26.409] (II) DAEMON: Adding new display on vt 1 ...
[21:30:26.410] (II) DAEMON: Display server starting...
[21:30:26.411] (EE) DAEMON: Failed to start display server process.
[21:30:26.411] (EE) DAEMON: Display server failed to start. Exiting

also the pacman -U *.pkg.tar.xz complains that I don't have 

ncurses5-compat-libs>=6

but I cannot find that within the pacman -Ss list ?

I am using 

pacman -Q ncurses
ncurses 6.0+20161224-1

I did try https://aur.archlinux.org/packages/ncurses5-compat-libs/

but had the issue of

==> Verifying source file signatures with gpg...
    ncurses-6.0-20161224.tgz ... FAILED (unknown public key 702353E0F7E48EDB)
==> ERROR: One or more PGP signatures could not be verified!

which appears to be downloading what I have already installed ? 

The dmesg was quoting

[   37.856567] sddm[532]: segfault at 7a0 ip 00000000000007a0 sp 00007ffed7d45258 error 14 in sddm[400000+72000]
[   39.625455] sddm[1597]: segfault at 1c88660 ip 0000000001c88660 sp 00007ffc3ce5b538 error 15
[   44.216735] sddm[1646]: segfault at 129f270 ip 000000000129f270 sp 00007ffd02f27f18 error 15
[   45.031028] sddm[2050]: segfault at 0 ip 00007fc3eb4a49d3 sp 00007fff50b45650 error 4 in libQt5Core.so.5.8.0[7fc3eb1ea000+4cc000]
[   48.490727] sddm[2122]: segfault at 30 ip 0000000000000030 sp 00007ffd0e299ce8 error 14 in sddm[400000+72000]
[   49.591808] sddm[2434]: segfault at 0 ip 00007ff3f7e6c9d3 sp 00007ffe1eb78040 error 4 in libQt5Core.so.5.8.0[7ff3f7bb2000+4cc000]
[   50.221142] sddm[2508]: segfault at 1f296e0 ip 0000000001f296e0 sp 00007ffe814234a8 error 15
[   52.116377] sddm[2630]: segfault at 30 ip 0000000000000030 sp 00007ffca3e332a8 error 14 in sddm[400000+72000]
[   52.626386] sddm[2733]: segfault at bd2b80 ip 0000000000bd2b80 sp 00007ffe26fb0838 error 15
[   54.370399] sddm[2755]: segfault at 0 ip           (null) sp 00007ffcb1701128 error 14 in sddm[400000+72000]

Is there any advice please :)

**Comment by JontySR** [comment]
I ran into the same PGP problem with ncurses5-compat-libs. I fixed it with the suggested method in the top comment on that package info page:

> To import the necessary key execute the following:
> gpg --recv-keys <KEYID - See 'validpgpkeys' variable in PKGBUILD>

I actually tried out sddm shortly after installing AMDGPU-Pro 16.60 and it worked, so I'd imagine getting those dependencies down for 16.60 would solve your issue. Other than that, make sure your xorg-server and xorg-server-common are 1.18.

**Comment by ianporter** [comment]
thanks very much for getting back to me so quickly.. I am at work, but shall try that out later :)

**Comment by brainpower** [comment]
To solve the PGP issue somehow permanently, one could also add/enable
<pre>
# auto-key-retrieve : automatically fetch keys as needed from the keyserver
keyserver-options auto-key-retrieve
</pre>
in ´~/.gnupg/gpg.conf`

**Comment by JontySR** [comment]
Thanks @brainpower, TIL.

**Comment by ianporter** [comment]
Thanks for the update.

I am getting this error upon trying to install the pro packages

:: xf86-video-amdgpu-pro and xorg-server are in conflict (X-ABI-VIDEODRV_VERSION). Remove xorg-server? [y/N] 

I would assume that I require xorg-server ?

**Comment by corngood** [comment]
@ianporter You probably just need to downgrade to xorg-server 1.18?  Did you do that already?

**Comment by ianporter** [comment]
Nope, I have not that :(

I was reading here : https://wiki.archlinux.org/index.php/AMD_Catalyst#Xorg_repositories but their is not a xorg-server 1.18 version..

Is there any recommendations on how to downgrade via pacman ? (if possible) that will always keep in line with the AMDGPU-PRO version ?

**Comment by JontySR** [comment]
@ianporter Add `Server=https://archive.archlinux.org/repos/2016/01/10/$repo/os/$arch` to your `/etc/pacman.d/mirrorlist` and temporarily comment out the others. This will tell pacman to use the repositories from that date. Use `pacman -Syy` to update the database to the new mirror.

Then (**after uninstalling any xf86-* packages you have**) you can use `pacman -S xorg` and select the whole group **apart from xf86-* packages**, because which the video packages will cause conflicts. Install an xf86-input-* package from the list though, you'll need one, probably libinput.
This will downgrade all xorg packages to the latest versions from the 10th of January 2016, which should include xorg-server 1.18*.

To use arch normally again after the install, you'll need to add `IgnoreGroup=xorg` to your /etc/pacman.conf, uncomment the servers you commented out in the mirrorlist, delete the server you added to the mirrorlist and run `pacman -Syy` again to update the database. This tells pacman to not upgrade xorg (which would break this driver version) but switch back to the new repositories.

The whole xorg group should now be downgraded successfully and you may install the driver. To update it in the future if need be, remove the `IgnoreGroup=xorg` line from pacman.conf.

Good luck :)

**Comment by ianporter** [comment]
@JontySR : thanks very much, that sorted it.
